var movies = [
  {
    img: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    name: "The Godfather",
    genres: ["Crime", "Drama"],
    summary: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    rating: 9.2,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    name: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    summary: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    rating: 8.9,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    name: "Interstellar",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    summary: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    rating: 8.7,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    name: "The Matrix",
    genres: ["Action", "Sci-Fi"],
    summary: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    rating: 8.7,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    name: "Forrest Gump",
    genres: ["Comedy", "Drama", "Romance"],
    summary: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    rating: 8.8,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    name: "The Dark Knight",
    genres: ["Action", "Crime", "Drama"],
    summary: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    rating: 9.0,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    name: "Inception",
    genres: ["Action", "Sci-Fi", "Thriller"],
    summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    rating: 8.8,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    name: "Fight Club",
    genres: ["Drama"],
    summary: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    rating: 8.8,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    name: "Goodfellas",
    genres: ["Biography", "Crime", "Drama"],
    summary: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
    rating: 8.7,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    name: "The Shawshank Redemption",
    genres: ["Drama"],
    summary: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    rating: 9.3,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/3m1FEJqFYazR4kiBQZBgdfVgu2B.jpg",
    name: "Gladiator",
    genres: ["Action", "Adventure", "Drama"],
    summary: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    name: "Titanic",
    genres: ["Drama", "Romance"],
    summary: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    rating: 7.9,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    name: "Avatar",
    genres: ["Action", "Adventure", "Fantasy"],
    summary: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    rating: 7.9,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/s2xc8yU6Ym3HxvZacY2iLYh8b3Y.jpg",
    name: "The Silence of the Lambs",
    genres: ["Crime", "Drama", "Thriller"],
    summary: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer who skins his victims.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6ejM3ZIJ.jpg",
    name: "Se7en",
    genres: ["Crime", "Drama", "Mystery"],
    summary: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    name: "The Usual Suspects",
    genres: ["Crime", "Mystery", "Thriller"],
    summary: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    name: "Braveheart",
    genres: ["Biography", "Drama", "History"],
    summary: "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ikzw2iLnrHrHYVedUo5TpFvR8c.jpg",
    name: "Saving Private Ryan",
    genres: ["Drama", "War"],
    summary: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    name: "Alien",
    genres: ["Horror", "Sci-Fi"],
    summary: "The crew of a commercial spacecraft encounters a deadly lifeform after investigating a mysterious transmission.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ecC4E2yA3Pc5VtLcN9JjWXsW7s.jpg",
    name: "The Shining",
    genres: ["Drama", "Horror"],
    summary: "A family heads to an isolated hotel for the winter where an evil spiritual presence influences the father into violence, while his psychic son sees horrific forebodings.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    name: "Apocalypse Now",
    genres: ["Drama", "Mystery", "War"],
    summary: "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    name: "Scarface",
    genres: ["Crime", "Drama"],
    summary: "In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.",
    rating: 8.3,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    name: "The Departed",
    genres: ["Crime", "Drama", "Thriller"],
    summary: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    name: "Whiplash",
    genres: ["Drama", "Music"],
    summary: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8EkxOUzox2CS2RM.jpg",
    name: "Joker",
    genres: ["Crime", "Drama", "Thriller"],
    summary: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society, and then embarks on a downward spiral of revolution and bloody crime.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    name: "Parasite",
    genres: ["Drama", "Thriller"],
    summary: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6ejM3ZIJ.jpg",
    name: "Django Unchained",
    genres: ["Drama", "Western"],
    summary: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ecC4E2yA3Pc5VtLcN9JjWXsW7s.jpg",
    name: "Inglourious Basterds",
    genres: ["Adventure", "Drama", "War"],
    summary: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same night.",
    rating: 8.3,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/s2xc8yU6Ym3HxvZacY2iLYh8b3Y.jpg",
    name: "The Prestige",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    summary: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ikzw2iLnrHrHYVedUo5TpFvR8c.jpg",
    name: "Memento",
    genres: ["Mystery", "Thriller"],
    summary: "A man with short-term memory loss attempts to track down his wife's murderer.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    name: "The Green Mile",
    genres: ["Crime", "Drama", "Fantasy"],
    summary: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    name: "The Intouchables",
    genres: ["Biography", "Comedy", "Drama"],
    summary: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    name: "Spirited Away",
    genres: ["Animation", "Adventure", "Family"],
    summary: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    name: "Your Name",
    genres: ["Animation", "Drama", "Fantasy"],
    summary: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6ejM3ZIJ.jpg",
    name: "Coco",
    genres: ["Animation", "Adventure", "Family"],
    summary: "A boy accidentally enters the Land of the Dead and needs the help of his deceased family to return to the living world.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ecC4E2yA3Pc5VtLcN9JjWXsW7s.jpg",
    name: "Up",
    genres: ["Animation", "Adventure", "Comedy"],
    summary: "A septuagenarian ties thousands of balloons to his house and flies to South America, but discovers a young stowaway.",
    rating: 8.3,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/s2xc8yU6Ym3HxvZacY2iLYh8b3Y.jpg",
    name: "Inside Out",
    genres: ["Animation", "Adventure", "Comedy"],
    summary: "The emotions of a young girl moving to a new city conflict on how to best navigate a new life.",
    rating: 8.2,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ikzw2iLnrHrHYVedUo5TpFvR8c.jpg",
    name: "Toy Story",
    genres: ["Animation", "Adventure", "Comedy"],
    summary: "A cowboy doll is threatened when a new spaceman action figure supplants him as the top toy in a boy's room.",
    rating: 8.3,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    name: "The Lion King",
    genres: ["Animation", "Adventure", "Drama"],
    summary: "A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and bravery.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    name: "Finding Nemo",
    genres: ["Animation", "Adventure", "Comedy"],
    summary: "A clown fish teams up with a forgetful blue tang to find his kidnapped son through the Great Barrier Reef.",
    rating: 8.2,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    name: "Ratatouille",
    genres: ["Animation", "Adventure", "Comedy"],
    summary: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.",
    rating: 8.1,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    name: "Howl's Moving Castle",
    genres: ["Animation", "Adventure", "Family"],
    summary: "A young woman is cursed with an old body by a spiteful witch, and finds shelter in the moving castle of a mysterious wizard.",
    rating: 8.2,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6ejM3ZIJ.jpg",
    name: "Princess Mononoke",
    genres: ["Animation", "Adventure", "Fantasy"],
    summary: "On a journey to find the cure for a curse, a young prince finds himself in the middle of a war between the forest gods and a mining colony.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ecC4E2yA3Pc5VtLcN9JjWXsW7s.jpg",
    name: "Grave of the Fireflies",
    genres: ["Animation", "Drama", "War"],
    summary: "A heartbreaking story of two siblings struggling to survive in Japan during World War II.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/s2xc8yU6Ym3HxvZacY2iLYh8b3Y.jpg",
    name: "The Pianist",
    genres: ["Biography", "Drama", "Music"],
    summary: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    rating: 8.5,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/ikzw2iLnrHrHYVedUo5TpFvR8c.jpg",
    name: "Schindler's List",
    genres: ["Biography", "Drama", "History"],
    summary: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    rating: 8.9,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    name: "The Sixth Sense",
    genres: ["Drama", "Mystery", "Thriller"],
    summary: "A boy who communicates with spirits seeks the help of a disheartened child psychologist.",
    rating: 8.2,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    name: "Oldboy",
    genres: ["Action", "Drama", "Mystery"],
    summary: "After being kidnapped and imprisoned for 15 years, a man is mysteriously released and sets out to find his captors.",
    rating: 8.4,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    name: "City of God",
    genres: ["Crime", "Drama"],
    summary: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    rating: 8.6,
  },
  {
    img: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    name: "Amélie",
    genres: ["Comedy", "Romance"],
    summary: "A shy waitress decides to change the lives of those around her for the better while struggling with her own isolation.",
    rating: 8.3,
  },
];

export default movies;